### ISSUE TITLE
WebSocket was closed before the connection was established

### ISSUE THREAD

**Issue by CraftingKahuka** [OscToys/OscGoesBrrr#14]
will not connect not sure why address and port match

**Comment by SenkyDragon** [comment]
We do not provide user support here on github. Please join the discord if you have questions.

**Comment by CraftingKahuka** [comment]
this app sucks won't even work

**Comment by SenkyDragon** [comment]
This is not a support forum, if you have trouble, please joing the discord and ask for assistance.
